# Generated by Django 5.0 on 2023-12-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0003_bed_details_model_comments_model_gallery_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_details_model',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
