# Generated by Django 4.2.6 on 2023-12-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0004_alter_hostel_details_model_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel_details_model',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='hostel_details_model',
            name='vaccancy',
        ),
        migrations.AddField(
            model_name='hostel_details_model',
            name='location',
            field=models.CharField(default='Hyderabad', max_length=50),
        ),
        migrations.AlterField(
            model_name='bed_details_model',
            name='bed_no',
            field=models.CharField(choices=[['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6']], max_length=10),
        ),
        migrations.AlterField(
            model_name='hostel_details_model',
            name='type_of_hostel',
            field=models.CharField(choices=[['Male', 'Male'], ['Female', 'Female'], ['Co_living', 'Co_living']], max_length=10),
        ),
        migrations.AlterField(
            model_name='occupied_details_model',
            name='gender',
            field=models.CharField(choices=[['Male', 'Male'], ['Female', 'Female'], ['others', 'others']], max_length=10),
        ),
    ]
