# Generated by Django 5.0 on 2023-12-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0005_remove_hostel_details_model_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel_details_model',
            name='image',
            field=models.ImageField(default='hostel/smart_home.jpg', upload_to='hostels/'),
            preserve_default=False,
        ),
    ]
