# Generated by Django 5.0 on 2023-12-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0006_hostel_details_model_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_no', models.PositiveBigIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
