# Generated by Django 5.0 on 2023-12-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_contact', models.PositiveBigIntegerField(unique=True)),
                ('c_dob', models.DateField()),
                ('c_address_proof', models.FileField(upload_to='')),
                ('c_aadhaar', models.PositiveBigIntegerField(unique=True)),
                ('c_image', models.ImageField(upload_to='')),
                ('c_address', models.CharField(max_length=100)),
                ('Duration_of_staying', models.PositiveBigIntegerField()),
                ('hostel_id', models.PositiveBigIntegerField()),
                ('room_id', models.PositiveIntegerField()),
                ('bed_id', models.PositiveIntegerField()),
                ('approved', models.BooleanField()),
                ('service_agreement', models.FileField(upload_to='')),
            ],
        ),
    ]
