# Generated by Django 5.0 on 2023-12-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customer_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_book',
            name='Duration_of_staying',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customer_book',
            name='c_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
