# Generated by Django 5.0 on 2023-12-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_customer_book_duration_of_staying_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_book',
            name='service_agreement',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
