# Generated by Django 5.0 on 2023-12-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_customer_book_service_agreement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_register',
        ),
    ]
